language: php

php: ["5.3", "5.4", "5.5", "5.6", "hhvm", "hhvm-nightly"]

matrix:
    allow_failures: [{"php": "hhvm"}, {"php": "hhvm-nightly"}]
    fast_finish: true

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.6
    - secure: "HZsPafLD/Tw8QB3wxiqUGpmawKoIoZuFanW8Tzve29IAnvjj4ulIxWnYMULQbe4wvukcUg9dkjZ5ltXMJVKeFh3jlrC5ejKWrTD0cCnpfxgkmACInh93+Jt0XhpT+5dbReblOKMFslkEJwJxPily4rocyXUVLiUIz4tQgWnxQtQ="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
