language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

matrix:
  # Use PHP 5.4 for coverage reporting.
  include:
    - php: 5.4
      env:
        - secure: "uPLx95WarAoGhlpuFMWo8WxLK1wKeKLSJ9i6YuHdVrE4oxkzO4Y8R1PPxBsR\nTMBmVFnnaGMfvpnqqMGIGSIp22OG5waQ4LO/DRfSLng2syIkCJLGpJA1hb8Q\nuLubj6LEsmG7Z4PlX89LEl3mwRT+Z/me0Tzkfsy5O5mhMPXqa50="

  # PHP 5.5 is still in alpha, so ignore build failures.
  allow_failures:
    - php: 5.5

install: composer install --dev --prefer-source
script:  ./vendor/bin/travis-build
